// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5vzmBWd2_yP6-NmcR62yh2DB0FqPZXzM',
    appId: '1:385395233213:web:b32cd9bb577c6f72f902d4',
    messagingSenderId: '385395233213',
    projectId: 'memorime-2f531',
    authDomain: 'memorime-2f531.firebaseapp.com',
    storageBucket: 'memorime-2f531.firebasestorage.app',
    measurementId: 'G-FPMFFMKJ00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABOg2iQY0SXIyr6FhIBteCcrDLtpr_QQk',
    appId: '1:385395233213:android:63eb0d0a198c964df902d4',
    messagingSenderId: '385395233213',
    projectId: 'memorime-2f531',
    storageBucket: 'memorime-2f531.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChy9PMDqJmybNMdaqRfRZxB1NNn9S2CGk',
    appId: '1:385395233213:ios:9e1c5553bec98958f902d4',
    messagingSenderId: '385395233213',
    projectId: 'memorime-2f531',
    storageBucket: 'memorime-2f531.firebasestorage.app',
    iosBundleId: 'com.example.memorimeV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChy9PMDqJmybNMdaqRfRZxB1NNn9S2CGk',
    appId: '1:385395233213:ios:9e1c5553bec98958f902d4',
    messagingSenderId: '385395233213',
    projectId: 'memorime-2f531',
    storageBucket: 'memorime-2f531.firebasestorage.app',
    iosBundleId: 'com.example.memorimeV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5vzmBWd2_yP6-NmcR62yh2DB0FqPZXzM',
    appId: '1:385395233213:web:0988681eb0f3ad10f902d4',
    messagingSenderId: '385395233213',
    projectId: 'memorime-2f531',
    authDomain: 'memorime-2f531.firebaseapp.com',
    storageBucket: 'memorime-2f531.firebasestorage.app',
    measurementId: 'G-BWCZMEKW66',
  );
}
